quarkus.http.port=8080

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=caritas

# JBDC
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/caritas-db

quarkus.hibernate-orm.schema-management.strategy=update

# Mailer
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=
quarkus.mailer.password=
quarkus.mailer.start-tLS=REQUIRED
quarkus.mailer.from=
quarkus.mailer.mock=false
quarkus.mailer.auth-methods=LOGIN